### ISSUE TITLE
Development setup incl. JSXC?

### ISSUE THREAD

**Issue by poVoq** [jsxc/jsxc-single-page#18]
More of a question, but is there an easy way to include a development version of JSXC itself in the development environment so that I can see live-update of any code changes similar to how I can modify files in the `src` directory of the single-page app and it will live-update in the local version that runs after `yarn start`.

By default it seems to only include a minified release version of JSXC that is not suitable for making changes to the upstream JSXC source itself.

(I want to improve the two-column layout, and that is defined upstream)

**Comment by sualko** [comment]
Nice to hear that there is some activity. That's always motivating.

To ease development you can use [yarn link](https://classic.yarnpkg.com/en/docs/cli/link/). It basically allows you to use a local version of any package. So you need this repo in one folder and jsxc in another. In the jsxc folder you execute `yarn link` and in the single page folder `yarn link @jsxc/jsxc`. Do create a new version of jsxc you have to call `yarn watch` (in the jsxc folder). I'm not sure if the file watcher of this repo is rebuilding everything on the fly, but that's the easiest solution I came up with.

Happy coding!

**Comment by poVoq** [comment]
Doesn't reload the remote directory automatically, but works. Thanks.
